services:

  postgres:
    image: postgres:17
    container_name: ai-taskmanager-postgres

    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-1234}

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USERNAME:-postgres} -d taskmanager"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: ai-taskmanager-backend

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskmanager
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-1234}

      AI_DEFAULT_PROVIDER: ${AI_DEFAULT_PROVIDER:-GEMINI}

      GEMINI_API_KEY: ${GEMINI_API_KEY:?Defina GEMINI_API_KEY no arquivo .env}
      GEMINI_MODEL: ${GEMINI_MODEL:-gemini-3.5-flash-lite}

      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL:-http://host.docker.internal:11434}
      OLLAMA_MODEL: ${OLLAMA_MODEL:-qwen2.5:3b}

    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy

    extra_hosts:
      - "host.docker.internal:host-gateway"


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: ai-taskmanager-frontend

    ports:
      - "3000:80"

    depends_on:
      - backend


volumes:
  postgres_data: