spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/taskmanager
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false

    properties:
      hibernate:
        format_sql: false

  ai:
    model:
      chat: ollama

    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}

      chat:
        model: ${OLLAMA_MODEL:qwen2.5:3b}

        # Mantém o modelo carregado entre as requisições.
        keep-alive: 30m

        # Fallback caso alguma operação não configure
        # parâmetros específicos.
        num-predict: 128
        num-ctx: 2048
        num-batch: 512
        num-thread: 6

        temperature: 0.1